BoxLayout:
#    Button:
#        color: (1,0,0,1)
#        text: "Convert"
#        size_hint_x: .3
#        on_press: app.handle_conversion()
    orientation: 'vertical'
    TextInput:
        id: celcius_value
        background_color: (10,10,10,0)
        font_size: 40
        on_text: app.convert_to_fahra(celcius_value.text)
    TextInput
        id: fahra_value
        background_color: (0,0,0,.8)
        font_size: 40
        on_text: app.convert_to_celcius()